DOMAIN = "gryf_smart"

CONF_LIGHTS = "lights"
CONF_BUTTON = "buttons"
CONF_NAME = "name"
CONF_ID = "id"
CONF_PIN = "pin"
CONF_SERIAL = "port"
CONF_DOORS = "doors"
CONF_WINDOW = "windows"
CONF_TEMPERATURE = "temperature"
CONF_COVER = "covers"
CONF_TIME = "time"
CONF_LOCK = "lock"
CONF_PWM = "pwm"
CONF_CLIMATE = "climate"
CONF_HARMONOGRAM = "harmonogram"

COVER_DEVICE_CLASS = "window"
