from homeassistant.components.climate.const import HVACMode , HVACAction 

CLIMATE_START_TEMPERATURE = 85
CLIMATE_START_TARGET_TEMPERATURE = 20
CLIMATE_MIN_TEMP = 5
CLIMATE_MAX_TEMP = 35

DEFAULT_HAVAC_MODE = HVACMode.OFF
DEFAULT_HAVAC_ACTION = HVACAction.IDLE
